# Generated by Django 6.0.7 on 2026-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioconfig',
            name='video_hero',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/hero/'),
        ),
    ]
