# Generated by Django 6.0.7 on 2026-08-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioconfig_video_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmedia',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/projects/video_thumbnails/'),
        ),
    ]
