# Generated by Django 6.0.7 on 2026-08-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projectmedia_miniatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioconfig',
            name='video_hero_mobile',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/hero/'),
        ),
    ]
